### ISSUE TITLE
Get rid of externally hosted assets

### ISSUE THREAD

**Issue by rzo1** [apache/apachecon-eu#1]
Due to EU privacy regulations we need to serve assets from our own web hosting instead of including it from CDNs.

Goal of this issue to get rid of externally included assets and serve every CSS/JS/Font from within our own webhosting.

**Comment by pedrogk** [comment]
Added fix on remove-external-assets branch

**Comment by rzo1** [comment]
Hey @pedrogk 

we still have some references to external assets:

![image](https://github.com/apache/apachecon-eu/assets/13417392/7387b5c6-1b63-462c-961a-22d44ab744b6)

Mostly (google) fonts and css + javascript.

**Comment by rzo1** [comment]
Let me know, if I can help.

**Comment by pedrogk** [comment]
Hadn't had a chance to work on this, but it should be ok now with the last pull request I sent.

**Comment by rzo1** [comment]
![image](https://github.com/apache/apachecon-eu/assets/13417392/3e5d77f8-bf3f-4faa-9fb3-1289d888d1bd)

Only a few fonts left. We are nearly there, @pedrogk 

fyi: @fpapon

**Comment by pedrogk** [comment]
Just pushed a fix to this. Sorry, forgot to create a branch for it and made the push to main. It is commit 5a8b261ee7733bb37ac6edc55158d9f03ad7581b

@rzo1

**Comment by rzo1** [comment]
Thx. Just synced the fork so the changes should become available soon @pedrogk

**Comment by rzo1** [comment]
Looks good. Closing, thanks @pedrogk
