### ISSUE TITLE
Add blog entry about ASF 25th Anniversary

### ISSUE THREAD

**Issue by Teyzalv** [apache/apachecon-eu#11]
Add blog entry about the ASF 25th Anniversary on [Latest news](https://docs.google.com/document/d/11BiFBB6EtIt5B1XBypbp4mX6zwN0HomOxWvQMHUyhZM/edit)

@AlbertoRJ

**Comment by pedrogk** [comment]
This has been done, with commit a6422d42e017dd69adb2152aa6207290d0d52cc6
