### ISSUE TITLE
Small updates

### ISSUE THREAD

**Issue by Teyzalv** [apache/apachecon-eu#18]
- Make the surname Van Gulik be in the same name level 

- Add an "H" to Ikegah 

- Replace the phrase: "Remember that our Call for Papers is still open and we will be announcing many more speakers soon" for "We will announce the full program soon". 

- Latest news: Replace "25th Anniversary of the ASF" for "25th ASF Anniversary" 

- Make two columns of the about the venue information with the images on the right 

@AlbertoRJ

**Comment by pedrogk** [comment]
It looks like this is done.
