### ISSUE TITLE
Upload TAC information 

### ISSUE THREAD

**Issue by Teyzalv** [apache/apachecon-eu#19]
Add a blog entry that redirects to [https://tac.apache.org/](url) 

Use this picture for the cover and add the text: Scholarships

 ![1700609293903](https://github.com/apache/apachecon-eu/assets/142928253/9b0f1549-f698-4727-8e0f-b4a644eb440b)

**Comment by Teyzalv** [comment]
@AlbertoRJ

**Comment by pedrogk** [comment]
A blog post cannot be a redirect. It needs to be a regular page with some text, and within the text you can add a link to https://tac.apache.org/ . But you need some kind of text/explanation in the blog post at this site. cc @AlbertoRJ @Teyzalv

**Comment by Teyzalv** [comment]
@pedrogk Got it, here's the text: https://docs.google.com/document/d/1fbRL7e_M0h83h1MCMjlj4232A2nbxj_GXp0_6gO07iE/edit 

@AlbertoRJ
